[
    {"title": "The Shawshank Redemption", "year": "1994"},
    {"title": "The Godfather", "year": "1972"},
    {"title": "The Godfather: Part II", "year": "1974"},
    {"title": "The Dark Knight", "year": "2008"},
    {"title": "Pulp Fiction", "year": "1994"},
    {"title": "Il buono, il brutto, il cattivo", "year": "1966"},
    {"title": "12 Angry Men", "year": "1957"},
    {"title": "Schindler’s List", "year": "1993"},
    {"title": "The Lord of the Rings: The Return of the King", "year": "2003"},
    {"title": "Fight Club", "year": "1999"},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "year": "2001"},
    {"title": "Star Wars: Episode V — The Empire Strikes Back", "year": "1980"},
    {"title": "Inception", "year": "2010"},
    {"title": "Interstellar", "year": "2014"},
    {"title": "Forrest Gump", "year": "1994"},
    {"title": "One Flew Over the Cuckoo’s Nest", "year": "1975"},
    {"title": "The Lord of the Rings: The Two Towers", "year": "2002"},
    {"title": "Goodfellas", "year": "1990"},
    {"title": "The Matrix", "year": "1999"},
    {"title": "Star Wars", "year": "1977"},
]